---
title: "Spatstat-correlation"
author: "Liangxiao LI"
date: "2023-07-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(spatstat)
library(readxl)
```

#Load data

```{r}
#Xiao
setwd("/Users/ryan/Documents/GitHub/Shenzhen Bay lab/spike_protein_3structures_markerd_with_variants_from_cncb")
data <- read_excel("6vxx_variants.xls")

data<-data[1:972,c("X","Y","Z","virusPercent")]

```


```{r}

k_num <- 5
ite <- 20

feature_vector <- data[,c("virusPercent")]
kmeans_result <- kmeans(feature_vector, centers = k_num, nstart = ite)

# Sort the cluster factor in ascending order of feature vector values
sorted_labels <- order(kmeans_result$centers)
kmeans_result$cluster <- factor(kmeans_result$cluster, levels = sorted_labels)

# Combine feature vector and cluster assignments
result <- cbind(feature_vector, kmeans_result$cluster)

# Plot the data with sorted cluster labels

result <- cbind(feature_vector,kmeans_result$cluster)
plot(result)

```
#By cluster label

```{r}
myppp <- ppp(x = data$X, y = data$Y, z = data$Z, marks =kmeans_result$cluster ,window = owin(c(100, 300), c(100, 300), c(100, 300))) #创建点模式对象
```


#by virus percentage

```{r}
myppp <- ppp(x = data$X, y = data$Y, z = data$Z, marks = data$virusPercent * 10 ,window = owin(c(100, 300), c(100, 300), c(100, 300))) #创建点模式对象
```

```{r}
mark_corr_func <- pcf(myppp)

plot(mark_corr_func)
```




#only consider the high mutation points

```{r}
#Xiao
setwd("/Users/ryan/Documents/GitHub/Shenzhen Bay lab/spike_protein_3structures_markerd_with_variants_from_cncb")
data <- read_excel("6vxx_variants.xls")

data<-data[1:972,c("X","Y","Z","virusPercent")]

# Filter rows based on the condition virusPercent > 0.01
selected_data <- data[data$virusPercent > 0.01, ]

```

#By virus percentage

```{r}
myppp <- ppp(x = selected_data$X, y = selected_data$Y, z = selected_data$Z, marks = selected_data$virusPercent * 10 ,window = owin(c(100, 300), c(100, 300), c(100, 300))) #创建点模式对象

```

```{r}
mark_corr_func <- pcf(myppp)

plot(mark_corr_func)
```

















```{r}
# Load required packages
library(spatstat)

# Generate some sample data
set.seed(123)
n <- 100
x <- rnorm(n)
y <- rnorm(n)
z <- rnorm(n)
clusters <- factor(sample(1:3, n, replace = TRUE))

# Create marked point pattern
myppp <- ppp(x = x, y = y, z = z, marks = clusters)

# Calculate the mark correlation function (pcf)
mark_corr_func <- pcf(myppp)

# Plot the mark correlation function
plot(mark_corr_func, main = "Mark Correlation Function", xlab = "Distance", ylab = "Correlation")
```






















```{r}
myK <- Kcross(myppp, myppp$marks) #计算不同标记值之间的K函数值
plot(myK, main = "Kcross Function", fvlabels = levels(myppp$marks))
```



```{r}
mypcf <- pcf(myppp) #计算点模式对象的空间自相关函数
plot(mypcf, main = "Pair Correlation Function") #绘制空间自相关函数图
```

```{r}
library(spatstat)
myppp <- ppp(x = data$X, y = data$Y, z = data$Z, marks = result[,2], check = FALSE) #创建点模式对象
myppp$marks <- cutree(hclust(dist(myppp$marks)), k = 5) #按照m的值进行聚类，分为3类，并将聚类结果赋值为点模式对象的marks属性

myK <- Kcross(myppp, myppp$marks) #计算不同标记值之间的K函数值
plot(myK, main = "Kcross Function", fvlabels = levels(myppp$marks))
```







```{r}
# Create a sample point pattern object with two mark types
library(spatstat)
mydata <- data.frame(x = runif(100), y = runif(100), z = runif(100), mark = factor(sample(1:2, 100, replace = TRUE)))
myppp <- ppp(x = mydata$x, y = mydata$y, z = mydata$z, marks = mydata$mark, check = FALSE)

# Compute the K-cross function
myK <- Kcross(myppp, myppp$marks)

# Plot the K-cross function
plot(myK, main = "K-cross Function")

```



```{r}
# Load the spatstat package
library(spatstat)

# Generate a synthetic three-dimensional point pattern with a uniform distribution
set.seed(123)
synthetic3d_pp <- rpoint(100, win = owin(c(0, 1), c(0, 1), c(0, 1)))

# Extract the x, y, and z coordinates from the point pattern object
x <- synthetic3d_pp$x
y <- synthetic3d_pp$y
z <- synthetic3d_pp$marks

# Plot the point pattern in 3D
plot3d(x, y, z, col = "blue", size = 2, main = "Synthetic 3D point pattern")

# Compute the K function for the point pattern
K <- Kest(synthetic3d_pp)

# Plot the K function
plot(K, main = "K function for synthetic 3D point pattern")
```




```{r}
# Load the spatstat package
library(spatstat)

# Generate a synthetic three-dimensional point pattern with a uniform distribution and a random mark
set.seed(123)
synthetic3d_pp <- rpoint(100, win = owin(c(0, 1), c(0, 1), c(0, 1),c(0,1)), marks = rnorm(100))

# Extract the x, y, and z coordinates and the mark values from the point pattern object
x <- synthetic3d_pp$x
y <- synthetic3d_pp$y
z <- synthetic3d_pp$z

# Plot the point pattern in 3D, using the mark values to color the points
plot3d(x, y, z, col = "blue", size = 2, main = "Synthetic 3D point pattern with random mark")

# Compute the mark correlation function for the point pattern
M <- markcorr(synthetic3d_pp, r = seq(0, 1, length = 50))

# Plot the mark correlation function
plot(M, main = "Mark correlation function for synthetic 3D point pattern")

# Generate a second synthetic three-dimensional point pattern with a uniform distribution and a different random mark
set.seed(456)
synthetic3d_pp2 <- rpoint(100, win = owin(c(0, 1), c(0, 1), c(0, 1)), marks = rnorm(100, mean = 2, sd = 0.5))

# Extract the x, y, and z coordinates and the mark values from the second point pattern object
x2 <- synthetic3d_pp2$x
y2 <- synthetic3d_pp2$y
z2 <- synthetic3d_pp2$marks

# Plot the second point pattern in 3D, using the mark values to color the points
plot3d(x2, y2, z2, col = z2, size = 2, main = "Second synthetic 3D point pattern with different mark")

# Compute the mark cross correlation function between the two point patterns
MC <- mccf(synthetic3d_pp, synthetic3d_pp2, r = seq(0, 1, length = 50))

# Plot the mark cross correlation function
plot(MC, main = "Mark cross correlation function between two synthetic 3D point patterns")
```

